Configurar la ruta PATH para chromedriver
Configurar la ruta PATH para chromedriver, sirve para poder usar un bot con selenium , tambien necesita tener instalado webdriver manager

Corrige el error:
 
Traceback (most recent call last):
  File "C:\Users\camac\miniconda3\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\camac\miniconda3\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\camac\miniconda3\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\camac\miniconda3\Lib\site-packages\selenium\bot.py", line 21, in <module>
    main()
  File "C:\Users\camac\miniconda3\Lib\site-packages\selenium\bot.py", line 18, in main
    browser = webdriver.Chrome()
  File "C:\Users\camac\miniconda3\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\camac\miniconda3\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home